export default {
    products:
    [
        {
            _id:'1',
            name : 'Women T-shirt1',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            rating: 4.6,
            numReviews: 10,
            countInStock:0,
        },
        {
            _id:'2',
            name : 'Women T-shirt2',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            rating: 4.6,
            numReviews: 10,
            countInStock:6,
        },
        {
            _id:'3',
            name : 'Women T-shirt3',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            rating: 4.6,
            numReviews: 10,
            countInStock:4,
        },
        {
            _id:'4',
            name : 'Women T-shirt4',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            rating: 4.6,
            numReviews: 10,
            countInStock:5,
        },
        {
            _id:'5',
            name : 'Women T-shirt5',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            rating: 4.6,
            numReviews: 10,
            countInStock:8,
        },
        {
            _id:'6',
            name : 'Women T-shirt6',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            rating: 4.6,
            numReviews: 10,
            countInStock:7,
        },
        {
            _id:'7',
            name : 'Women T-shirt7',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            rating: 4.6,
            numReviews: 10,
            countInStock:3,
        },
        {
            _id:'8',
            name : 'Women T-shirt8',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            rating: 4.6,
            numReviews: 10,
            countInStock:5,
        }
        
    ]
}