export default {
    products:
    [
        {
            _id:'1',
            name : 'Women T-shirt',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            status:'In Stock',
            rating: 4.6,
            numReviews: 10,
            countInStock:5,
        },
        {
            _id:'2',
            name : 'Women T-shirt',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            status:'In Stock',
            rating: 4.6,
            numReviews: 10,
            countInStock:9,
        },
        {
            _id:'3',
            name : 'Women T-shirt',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            status:'In Stock',
            rating: 4.6,
            numReviews: 10,
            countInStock:7,
        },
        {
            _id:'4',
            name : 'Women T-shirt',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            status:'In Stock',
            rating: 4.6,
            numReviews: 10,
            countInStock:4,
        },
        {
            _id:'5',
            name : 'Women T-shirt',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            status:'In Stock',
            rating: 4.6,
            numReviews: 10,
            countInStock:6,
        },
        {
            _id:'6',
            name : 'Women T-shirt',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            status:'In Stock',
            rating: 4.6,
            numReviews: 10,
            countInStock:10,
        },
        {
            _id:'7',
            name : 'Women T-shirt',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            status:'In Stock',
            rating: 4.6,
            numReviews: 10,
            countInStock:8,
        },
        {
            _id:'8',
            name : 'Women T-shirt',
            image: '/images/product1.jpg',
            price: 60,
            brand: 'Adidas',
            description:'Nice T-shirt',
            status:'In Stock',
            rating: 4.6,
            numReviews: 10,
            countInStock:3,
        }
        
    ]
}